#The WinshipCARS_APE2021 SQL file was used to deliver distinct counts of cancer diagnoses per person represented in the CARS database. 

--Winship CARS Cancer Cohort Profile

SELECT
	DISTINCT p.PERSON_ID
FROM
	WINSHIPCARS.PERSON p
---422,735
	
	
	
-----BREAST------
 	
SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	CONDITION_CONCEPT_ID IN (
	SELECT
ca.DESCENDANT_CONCEPT_ID
FROM
WINSHIPCARS.CONCEPT_ANCESTOR ca
WHERE
ANCESTOR_CONCEPT_ID = 4112853)
GROUP BY
co.PERSON_ID
ORDER BY
PERSON_ID
----As of 08/31/21, 26,189 patients with breast cancer in CARS ; Proportion to overall data (422,735) = 0.06195


----LUNG -----

SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	CONDITION_CONCEPT_ID IN (
	SELECT
ca.DESCENDANT_CONCEPT_ID
FROM
WINSHIPCARS.CONCEPT_ANCESTOR ca
WHERE
ANCESTOR_CONCEPT_ID = 4311499)
GROUP BY
co.PERSON_ID
ORDER BY
PERSON_ID

----As of 08/31/21, 20,034 patients with lung cancer in CARS ; Proportion to overall data (422,735) = 0.04739




----PROSTATE -----

SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	CONDITION_CONCEPT_ID IN (
	SELECT
ca.DESCENDANT_CONCEPT_ID
FROM
WINSHIPCARS.CONCEPT_ANCESTOR ca
WHERE
ANCESTOR_CONCEPT_ID = 4163261)
GROUP BY
co.PERSON_ID
ORDER BY
PERSON_ID

----As of 08/31/21, 21,358  patients with  prostate cancer in CARS ; Proportion to overall data (422,735) = 0.05052



----COLON -----

SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	CONDITION_CONCEPT_ID IN (
	SELECT
ca.DESCENDANT_CONCEPT_ID
FROM
WINSHIPCARS.CONCEPT_ANCESTOR ca
WHERE
ANCESTOR_CONCEPT_ID = 4180790)
GROUP BY
co.PERSON_ID
ORDER BY
PERSON_ID


----As of 08/31/21, 10,613  patients with colon cancer in CARS ; Proportion to overall data (422,735) = 0.02510556

******CONDITIONS*******

SELECT
	*
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
	
	--59,172,389--- 

WITH breast_cancer AS (
SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	co.CONDITION_CONCEPT_ID IN (
	SELECT
		ca.DESCENDANT_CONCEPT_ID
	FROM
		WINSHIPCARS.CONCEPT_ANCESTOR ca
	WHERE
		ANCESTOR_CONCEPT_ID = 4112853)
GROUP BY
	co.PERSON_ID
ORDER BY
	PERSON_ID)
SELECT
	*
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
INNER JOIN breast_cancer bc ON
	co.PERSON_ID = bc.person_id
	
	--7,379,906 breast conditions of 59,172,389 total conditions = 0.1247

	
	
	
	**PROCEDURES****
	
	SELECT
	*
FROM
	WINSHIPCARS.PROCEDURE_OCCURRENCE po
	---42,271,463
	
WITH breast_cancer_cohort AS (
SELECT
	co.PERSON_ID
FROM
	WINSHIPCARS.CONDITION_OCCURRENCE co
WHERE
	co.CONDITION_CONCEPT_ID IN (
	SELECT
		ca.DESCENDANT_CONCEPT_ID
	FROM
		WINSHIPCARS.CONCEPT_ANCESTOR ca
	WHERE
		ANCESTOR_CONCEPT_ID = 4112853)
GROUP BY
	co.PERSON_ID
ORDER BY
	PERSON_ID)
SELECT
	*
FROM
	WINSHIPCARS.PROCEDURE_OCCURRENCE po
INNER JOIN breast_cancer_cohort bc ON
	po.PERSON_ID = bc.person_id
	
	-- 3,794,949 procedures for breast cancer patients ~9%
